# Generated by Django 3.1.1 on 2020-09-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
