# Generated by Django 3.1.1 on 2020-09-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Chennai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(default='A+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='9791684645', max_length=20),
            preserve_default=False,
        ),
    ]
